export const books = [
  {
    "id": "1",
    "title": "Toward a Threefold Society",
    "global": {
      "Author": "Rudolf Steiner",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Translator": "Frank Thomas Smith",
      "publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "pages": "176",
      "publication date": "December 10, 2019",
      "dimensions": "5.5 x 0.4 x 8.5 inches",
      "shipping weight": "11.6 ounces",
      "ISBN-10": "1-948302-16-6",
      "ISBN-13": "978-1-948302-16-6",
    },
    "kindle": {
      "size": "999kb",
      "publication date": "December 11, 2019",
      "text-to-speech": "enabled",
      "x-ray": "not enabled",
      "word wise": "enabled",
      "lending": "enabled",
      "simultaneous device usage": "unlimited",
      "enhanced typesetting": "enabled",
      "ISBN-10": "1-948302-17-3",
      "ISBN-13": "978-1-948302-17-3",
    },
    "categories": ["Social Science", "Modern Translations"],
    "url": "https://amzn.to/2P4pMnx",
    "img": "towthreesociety_covs.jpg",
    "online": "no"
  },
  {
    "id": "2",
    "title": "The Worldview of Herman Grimm",
    "sub-title": "in Relation to Spiritual Science",
    "global": {
      "Author": "Rudolf Steiner",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Translator": "Peter Stebbing",
      "publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "pages": "52",
      "publication date": "November 13, 2019",
      "dimensions": "5.5 x 0.13 x 8.5 inches",
      "ISBN-10": "1-948302-12-8",
      "ISBN-13": "978-1-948302-12-8",
    },
    "kindle": {
      "Size": "810kb",
      "Publication Date": "December 11, 2019",
      "Text-to-Speech": "enabled",
      "X-Ray": "enabled",
      "Word Wise": "enabled",
      "Lending": "enabled",
      "Simultaneous Device Usage": "Unlimited",
      "Enhanced Typesetting": "Not Enabled",
      "ISBN-10": "1-948302-13-6",
      "ISBN-13": "978-1-948302-13-5",
    },
    "url": "https://amzn.to/36rj94r",
    "img": "hermangrimm01_covs.jpg",
    "categories": ["Modern Translations"],
    "online": "https://wn.rsarchive.org/Lectures/GA062/English/eLib2019b/GrimmH_index.html"
  },
  {
    "id": "3",
    "title": "Anthroposophical Fantasies",
    "global": {
      "Author": "Frank Thomas Smith",
      "Alter Ego": "Roberto Fox",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Ilustrator": "Celina MacKern",
    },
    "paperback": {
      "Pages": "232",
      "Publication Date": "August 16, 2019",
      "Product Dimensions": "5.5 x 0.6 x 8.5 inches",
      "Shipping Weight": "12.8 ounces",
      "ISBN-10": "1948302101",
      "ISBN-13": "978-1948302104",
    },
    "kindle": {
      "Size": "999kb",
      "Publication Date": "August 15, 2019",
      "Text-to-Speech": "enabled",
      "X-Ray": "not enabled",
      "Word Wise": "enabled",
      "Lending": "enabled",
      "Simoultaneous Device Usage": "unlimited",
      "Enhanced Typesetting": "enabled",
      "ISBN-10": "1948302111",
      "ISBN-13": "978-194830211X",
    },
    "url": "https://amzn.to/2Qcs1ba",
    "img": "AnthroFantasies_covs.jpg",
    "categories": ["Fiction"],
    "online": "no"
  },
  {
    "id": "4",
    "title":
      "Fairy Tales",
    "sub-title": "in the Light of Spiritual Investigation and A Mongolian Legend:",
    "global": {
      "Author": "Rudolf Steiner",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Translator": "Peter Stebbing",
    },
    "paperback": {
      "Pages": "42",
      "Publication Date": "August 21, 2019",
      "Product Dimensions": "5.5 x 0.1 x 8.5 inches",
      "ISBN-10": "1948302128",
      "ISBN-13": "978-1948302128",
    },
    "kindle": {
      "Size": "218 KB",
      "Publication Date": "August 22, 2019",
      "Text-to-Speech": "Enabled",
      "X-Ray": "Not Enabled",
      "Word Wise": "Enabled",
      "Lending": "Enabled",
      "Simoultaneous Device Usage": "Unlimited",
      "Enhanced Typesetting": "Enabled",
      "ISBN-10": "1948302128",
      "ISBN-13": "978-1948302128",
    },
    "url": "https://amzn.to/3lHrKZ2",
    "img": "FairyTales1_covs.jpg",
    "categories": ["Modern Translations"],
    "online": "https://wn.rsarchive.org/Lectures/GA062/English/eLib2019a/FairTl_index.html"
  },
  {
    "id": "5",
    "title":
      "Leonardo's Spiritual Stature",
    "sub-title": "at the Turning Point of Modern Times",
    "global": {
      "Author": "Rudolf Steiner",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Translator": "Peter Stebbing",
      "Ilustrator": "Leonardo da Vinci",
    },
    "paperback": {
      "Pages": "40",
      "Publication Date": "June 26, 2019",
      "Product Dimensions": "5.5 x 0.1 x 8.5 inches",
      "ISBN-10": "1948302098",
      "ISBN-13": "978-1948302098",
    },
    "kindle": {
      "Size": "1006 KB",
      "Publication Date": "August 19, 2019",
      "Text-to-Speech": "Enabled ",
      "X-Ray": "Not Enabled",
      "Word Wise": "Enabled",
      "Lending": "Enabled",
      "Simoultaneous Device Usage": "Unlimited",
      "Enhanced Typesetting": "Not Enabled ",
      "ISBN-10": "1948302098",
      "ISBN-13": "978-1948302098",
    },
    "url": "https://amzn.to/2Odm4rV",
    "img": "leonardostature_covs.jpg",
    "categories": ["Modern Translations"],
    "online": "https://wn.rsarchive.org/Lectures/GA062/English/eLib2019/Leondo_index.html"
  },
  {
    "id": "6",
    "title": "The Impulse of Renewal for Culture and Science",
    "global": {
      "Author": "Rudolf Steiner",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Translator": "Hanna von Maltitz",
    },
    "paperback": {
      "Pages": "149",
      "Product Dimensions": "5.5 x 0.4 x 8.5 inches",
      "ISBN-10": "1948302047",
      "ISBN-13": "978-1948302043",
    },
    "url": "https://amzn.to/2U5g30b",
    "img": "impulse4renewal_covs.jpg",
    "categories": ["Social Science", "Modern Translations"],
    "online": "https://wn.rsarchive.org/Lectures/GA081/English/eLib2018/ImpRen_index.html"
  },
  {
    "id": "7",
    "title": "Raphael's Mission",
    "sub-title": "in the Light of the Science of the Spirit",
    "global": {
      "Author": "Rudolf Steiner",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Translator": "Peter Stebbing",
    },
    "paperback": {
      "Pages": "44",
      "Product Dimensions": "5.5 x 0.1 x 8.5 inches",
      "ISBN-10": "1948302020",
      "ISBN-13": "978-1948302029",
    },
    "url": "https://amzn.to/2tAYXvO",
    "img": "raphaelsmission_covs.jpg",
    "categories": ["Modern Translations"],
    "online": "https://wn.rsarchive.org/Lectures/GA062/English/eLib2018/RapMis_index.html"
  },
  {
    "id": "8",
    "title": "The Social Question",
    "global": {
      "Author": "Rudolf Steiner",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Translator": "Hanna von Maltitz",
      "Ilustrator": "Hanna von Maltitz",
    },
    "paperback": {
      "Pages": "158",
      "Publication Date": "December 9, 2018",
      "Product Dimensions": "5.5 x 0.4 x 8.5 inches",
      "ISBN-10": "1791660533",
      "ISBN-13": "978-1791660536",
    },
    "kindle": {
      "Size": "810 KB",
      "Publication Date": "December 9, 2018",
      "Text-to-Speech": "Enabled",
      "X-Ray": "Enabled",
      "Word Wise": "Enabled",
      "Lending": "Enabled",
      "Simoultaneous Device Usage": "Unlimited",
      "Enhanced Typesetting": "Not Enabled",
      "ISBN-10": "1948302012",
      "ISBN-13": "978-1948302012",
    },
    "url": "https://amzn.to/2XkGvFp",
    "img": "thesocialquestion2_covs.jpg",
    "categories": ["Social Science", "Modern Translations"],
    "online": "https://wn.rsarchive.org/Lectures/GA328/English/eLib2017/SoQues_index.html"
  },
  {
    "id": "9",
    "title": "Favela Children",
    "sub-title": "A Brazilian Diary",
    "global": {
      "Author": "Ute Creamer",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Translator": "Frank Thomas Smith",
    },
    "paperback": {
      "Pages": "",
      "Publication Date": "",
      "Product Dimensions": "",
      "Shipping Weight": "",
      "ISBN-10": "",
      "ISBN-13": "",
    },
    "kindle": {
      "Size": "",
      "Publication Date": "",
      "Text-to-Speech": "",
      "X-Ray": "",
      "Word Wise": "",
      "Lending": "",
      "Simoultaneous Device Usage": "",
      "Enhanced Typesetting": "",
      "ISBN-10": "",
      "ISBN-13": "",
    },
    "url": "",
    "img": "favelachildren_covs.png",
    "categories": ["Social Science"],
    "online": "no"
  },
  {
    "id": "10",
    "title": "The Magic Mound",
    "global": {
      "Author": "Frank Thomas Smith",
      "Editor": "James D. Stewart",
      "Language": "English",
    },
    "paperback": {
      "Pages": "",
      "Publication Date": "",
      "Product Dimensions": "",
      "Shipping Weight": "",
      "ISBN-10": "",
      "ISBN-13": "",
    },
    "kindle": {
      "Size": "",
      "Publication Date": "",
      "Text-to-Speech": "",
      "X-Ray": "",
      "Word Wise": "",
      "Lending": "",
      "Simoultaneous Device Usage": "",
      "Enhanced Typesetting": "",
      "ISBN-10": "",
      "ISBN-13": "",
    },
    "url": "",
    "img": "magicmound_covs.png",
    "categories": ["Fiction", "Children's Books"],
    "online": "no"
  },
]
