export const books = [
  {
    "id": "1",
    "title": "Toward a Threefold Society",
    "tsort": "Toward Threefold Society",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Frank Thomas Smith",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "pages": "176",
      "publication date": "December 10, 2019",
      "dimensions": "5.5 x 0.4 x 8.5 inches",
      "shipping weight": "11.6 ounces",
      "ISBN-10": "1-948302-16-6",
      "ISBN-13": "978-1-948302-16-6",
      "url": "https://amzn.to/2P4pMnx",
    },
    "hardcover": {
      "type": "Hardcover",
      "pages": "176",
      "publication date": "September 10, 2021",
      "dimensions": "5.5 x 0.4 x 8.5 inches",
      "shipping weight": "11.6 ounces",
      "ISBN-10": "1-948302-19-7",
      "ISBN-13": "978-1-948302-19-7",
      "url": "https://amzn.to/3kEOA52",
    },
    "kindle": {
      "type": "Kindle",
      "size": "999kb",
      "publication date": "December 11, 2019",
      "text-to-speech": "enabled",
      "x-ray": "not enabled",
      "word wise": "enabled",
      "lending": "enabled",
      "simultaneous device usage": "unlimited",
      "enhanced typesetting": "enabled",
      "ISBN-10": "1-948302-17-3",
      "ISBN-13": "978-1-948302-17-3",
      "url": "https://amzn.to/3ChR92P",
    },
    "categories": [
      "Social Science",
      "Spiritual Science",
      "Modern Translations",
    ],
    "img": "towthreesociety_covs.jpg",
    "online": "",
    "carousel": true,
  },
  {
    "id": "2",
    "title": "The Worldview of Herman Grimm",
    "tsort": "Grimm Herman",
    "sub-title": "in Relation to Spiritual Science",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Peter Stebbing",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "pages": "52",
      "publication date": "November 13, 2019",
      "dimensions": "5.5 x 0.13 x 8.5 inches",
      "ISBN-10": "1-948302-12-8",
      "ISBN-13": "978-1-948302-12-8",
      "url": "https://amzn.to/36rj94r",
    },
    "kindle": {
      "type": "Kindle",
      "Size": "810kb",
      "Publication Date": "December 11, 2019",
      "Text-to-Speech": "enabled",
      "X-Ray": "enabled",
      "Word Wise": "enabled",
      "Lending": "enabled",
      "Simultaneous Device Usage": "Unlimited",
      "Enhanced Typesetting": "Not Enabled",
      "ISBN-10": "1-948302-13-6",
      "ISBN-13": "978-1-948302-13-5",
      "url": "",
    },
    "img": "hermangrimm01_covs.jpg",
    "categories": ["Spiritual Science", "Modern Translations"],
    "online":
      "https://wn.rsarchive.org/Lectures/GA062/English/eLib2019b/GrimmH_index.html",
    "carousel": true,
  },
  {
    "id": "3",
    "title": "Anthroposophical Fantasies",
    "tsort": "Anthroposophical Fantasies",
    "global": {
      "Author": "Frank Thomas Smith",
      "Alter Ego": "Roberto Fox",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Ilustrator": "Celina MacKern",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "Pages": "232",
      "Publication Date": "August 16, 2019",
      "Product Dimensions": "5.5 x 0.6 x 8.5 inches",
      "Shipping Weight": "12.8 ounces",
      "ISBN-10": "1948302101",
      "ISBN-13": "978-1948302104",
      "url": "https://amzn.to/2Qcs1ba",
    },
    "kindle": {
      "type": "Kindle",
      "Size": "999kb",
      "Publication Date": "August 15, 2019",
      "Text-to-Speech": "enabled",
      "X-Ray": "not enabled",
      "Word Wise": "enabled",
      "Lending": "enabled",
      "Simoultaneous Device Usage": "unlimited",
      "Enhanced Typesetting": "enabled",
      "ISBN-10": "1948302111",
      "ISBN-13": "978-194830211X",
      "url": "https://amzn.to/3HpHlHR",
    },
    "img": "AnthroFantasies_covs.jpg",
    "categories": ["Fantasy", "Fiction"],
    "online": "",
    "carousel": true,
  },
  {
    "id": "4",
    "title": "Fairy Tales",
    "tsort": "Fairy Tales",
    "sub-title":
      "in the Light of Spiritual Investigation and A Mongolian Legend:",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Peter Stebbing",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "Pages": "42",
      "Publication Date": "August 21, 2019",
      "Product Dimensions": "5.5 x 0.1 x 8.5 inches",
      "ISBN-10": "1948302128",
      "ISBN-13": "978-1948302128",
      "url": "https://amzn.to/3kI6xQ3",
    },
    "kindle": {
      "type": "Kindle",
      "Size": "218 KB",
      "Publication Date": "August 22, 2019",
      "Text-to-Speech": "Enabled",
      "X-Ray": "Not Enabled",
      "Word Wise": "Enabled",
      "Lending": "Enabled",
      "Simoultaneous Device Usage": "Unlimited",
      "Enhanced Typesetting": "Enabled",
      "ISBN-10": "1948302128",
      "ISBN-13": "978-1948302128",
      "url": "https://amzn.to/3lHrKZ2",
    },
    "img": "FairyTales1_covs.jpg",
    "categories": ["Spiritual Science", "Modern Translations"],
    "online":
      "https://wn.rsarchive.org/Lectures/GA062/English/eLib2019a/FairTl_index.html",
    "carousel": true,
  },
  {
    "id": "5",
    "title": "Leonardo's Spiritual Stature",
    "tsort": "Leonardo's Spiritual Stature",
    "sub-title": "at the Turning Point of Modern Times",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Peter Stebbing",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Ilustrator": "Leonardo da Vinci",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "Pages": "40",
      "Publication Date": "June 26, 2019",
      "Product Dimensions": "5.5 x 0.1 x 8.5 inches",
      "ISBN-10": "1948302098",
      "ISBN-13": "978-1948302098",
      "url": "https://amzn.to/2Odm4rV",
    },
    "kindle": {
      "type": "Kindle",
      "Size": "1006 KB",
      "Publication Date": "August 19, 2019",
      "Text-to-Speech": "Enabled ",
      "X-Ray": "Not Enabled",
      "Word Wise": "Enabled",
      "Lending": "Enabled",
      "Simoultaneous Device Usage": "Unlimited",
      "Enhanced Typesetting": "Not Enabled ",
      "ISBN-10": "1948302098",
      "ISBN-13": "978-1948302098",
      "url": "https://amzn.to/2YQ5E05",
    },
    "img": "leonardostature_covs.jpg",
    "categories": ["Spiritual Science", "Modern Translations"],
    "online":
      "https://wn.rsarchive.org/Lectures/GA062/English/eLib2019/Leondo_index.html",
    "carousel": true,
  },
  {
    "id": "6",
    "title": "The Impulse of Renewal for Culture and Science",
    "tsort": "Impulse Renewal Culture Science",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Hanna von Maltitz",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "Pages": "149",
      "Product Dimensions": "5.5 x 0.4 x 8.5 inches",
      "ISBN-10": "1948302047",
      "ISBN-13": "978-1948302043",
      "url": "https://amzn.to/2U5g30b",
    },
    "img": "impulse4renewal_covs.jpg",
    "categories": [
      "Social Science",
      "Spiritual Science",
      "Modern Translations",
    ],
    "online":
      "https://wn.rsachive.org/Lectures/GA081/English/eLib2018/ImpRen_index.html",
    "carousel": true,
  },
  {
    "id": "7",
    "title": "Raphael's Mission",
    "tsort": "Raphael's Mission",
    "sub-title": "in the Light of the Science of the Spirit",
    "global": {
      "Author": "Rudolf Steiner",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Translator": "Peter Stebbing",
    },
    "paperback": {
      "type": "Paperback",
      "Pages": "44",
      "Product Dimensions": "5.5 x 0.1 x 8.5 inches",
      "ISBN-10": "1948302020",
      "ISBN-13": "978-1948302029",
      "url": "https://amzn.to/2tAYXvO",
    },
    "img": "raphaelsmission_covs.jpg",
    "categories": ["Spiritual Science", "Modern Translations"],
    "online":
      "https://wn.rsarchive.org/Lectures/GA062/English/eLib2018/RapMis_index.html",
  },
  {
    "id": "8",
    "title": "The Social Question",
    "tsort": "Social Question",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Hanna von Maltitz",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Ilustrator": "Hanna von Maltitz",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "Pages": "158",
      "Publication Date": "December 9, 2018",
      "Product Dimensions": "5.5 x 0.4 x 8.5 inches",
      "ISBN-10": "1791660533",
      "ISBN-13": "978-1791660536",
      "url": "https://amzn.to/2XkGvFp",
    },
    "kindle": {
      "type": "Kindle",
      "Size": "810 KB",
      "Publication Date": "December 9, 2018",
      "Text-to-Speech": "Enabled",
      "X-Ray": "Enabled",
      "Word Wise": "Enabled",
      "Lending": "Enabled",
      "Simoultaneous Device Usage": "Unlimited",
      "Enhanced Typesetting": "Not Enabled",
      "ISBN-10": "1948302012",
      "ISBN-13": "978-1948302012",
      "url": "https://amzn.to/326hcxC",
    },
    "img": "thesocialquestion2_covs.jpg",
    "categories": [
      "Social Science",
      "Spiritual Science",
      "Modern Translations",
    ],
    "online":
      "https://wn.rsarchive.org/Lectures/GA328/English/eLib2017/SoQues_index.html",
  },
  {
    "id": "9",
    "title": "Favela Children",
    "tsort": "Favela Children",
    "sub-title": "A Brazilian Diary",
    "global": {
      "Author": "Ute Creamer",
      "Translator": "Frank Thomas Smith",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "Pages": "",
      "Publication Date": "",
      "Product Dimensions": "",
      "Shipping Weight": "",
      "ISBN-10": "",
      "ISBN-13": "",
      "url": "",
    },
    "kindle": {
      "type": "Kindle",
      "Size": "",
      "Publication Date": "",
      "Text-to-Speech": "",
      "X-Ray": "",
      "Word Wise": "",
      "Lending": "",
      "Simoultaneous Device Usage": "",
      "Enhanced Typesetting": "",
      "ISBN-10": "",
      "ISBN-13": "",
      "url": "",
    },
    "img": "favelachildren_covs.png",
    "categories": ["Social Science", "Coming Soon"],
    "online": "",
  },
  {
    "id": "10",
    "title": "The Magic Mound",
    "tsort": "Magic Mound",
    "global": {
      "Author": "Frank Thomas Smith",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Anthroposophical Publications",
    },
    "paperback": {
      "type": "Paperback",
      "Pages": "",
      "Publication Date": "",
      "Product Dimensions": "",
      "Shipping Weight": "",
      "ISBN-10": "",
      "ISBN-13": "",
      "url": "",
    },
    "kindle": {
      "type": "Kindle",
      "Size": "",
      "Publication Date": "",
      "Text-to-Speech": "",
      "X-Ray": "",
      "Word Wise": "",
      "Lending": "",
      "Simoultaneous Device Usage": "",
      "Enhanced Typesetting": "",
      "ISBN-10": "",
      "ISBN-13": "",
      "url": "",
    },
    "img": "magicmound_covs.png",
    "categories": ["Fiction", "Children's Books", "Coming Soon"],
    "online": "",
  },
  {
    "id": "11",
    "title": "The History and Actuality of Imperialism",
    "tsort": "History Actuality Imperialism",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Frank Thomas Smith",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "pages": "53",
      "publication date": "August 17, 2020",
      "dimensions": "5.5 x 0.2 x 8.5 inches",
      "shipping weight": "8.6 ounces",
      "ISBN-10": "1-948302-20-3",
      "ISBN-13": "978-1-948302-20-3",
      "url": "",
    },
    "kindle": {
      "type": "eBook",
      "size": "702kb",
      "publication date": "December 11, 2019",
      "text-to-speech": "enabled",
      "x-ray": "not enabled",
      "word wise": "enabled",
      "lending": "enabled",
      "simultaneous device usage": "unlimited",
      "enhanced typesetting": "enabled",
      "ISBN-10": "1-948302-20-0",
      "ISBN-13": "978-1-948302-20-0",
      "url": "https://amzn.to/3jPhtLQ",
    },
    "categories": [
      "Social Science",
      "Spiritual Science",
      "Modern Translations",
    ],
    "img": "the-history-and-actuality-of-imperialism.jpg",
    "online":
      "https://wn.rsarchive.org/Lectures/GA196/English/SCR2011/HisImp_index.html",
  },
  {
    "id": "12",
    "title":
      "Esoteric Lessons for the First Class of the Free School for Spiritual Science at the Goetheanum (Volume One)",
    "tsort":
      "Esoteric Lessons First Class Free School Spiritual Science Goetheanum Volume 1",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Frank Thomas Smith",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Anthroposophical Publications",
    },
    "paperback": {
      "type": "Paperback",
      "pages": "118",
      "publication date": "September 15, 2021",
      "dimensions": "6 x 0.5 x 9 inches",
      "shipping weight": "8.6 ounces",
      "ISBN-10": "1-948302-28-9",
      "ISBN-13": "978-1-948302-28-9",
      "url": "",
    },
    "hardcover": {
      "type": "Hardcover",
      "pages": "118",
      "publication date": "September 15, 2021",
      "dimensions": "6 x 0.5 x 9 inches",
      "shipping weight": "8.6 ounces",
      "ISBN-10": "1-948302-45-6",
      "ISBN-13": "978-1-948302-45-6",
      "url": "",
    },
    "kindle": {
      "type": "eBook",
      "size": "1971kb",
      "publication date": "September 15, 2021",
      "text-to-speech": "enabled",
      "x-ray": "not enabled",
      "word wise": "enabled",
      "lending": "enabled",
      "simultaneous device usage": "unlimited",
      "enhanced typesetting": "enabled",
      "ISBN-10": "1-948302-27-2",
      "ISBN-13": "978-1-948302-27-2",
      "url": "https://amzn.to/2WXah7R",
    },
    "categories": ["Philosophy", "Spiritual Science", "Modern Translations"],
    "img": "FirstClass09b_cov.jpg",
    "online":
      "https://wn.rsarchive.org/Lectures/GA270/English/eLib2018a/FstCs1_index.html",
  },
  {
    "id": "13",
    "title":
      "Esoteric Lessons for the First Class of the Free School for Spiritual Science at the Goetheanum (Volume Two)",
    "tsort":
      "Esoteric Lessons First Class Free School Spiritual Science Goetheanum Volume 2",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Frank Thomas Smith",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Anthroposophical Publications",
    },
    "paperback": {
      "type": "Paperback",
      "pages": "121",
      "publication date": "November 15, 2021",
      "dimensions": "6 x 0.5 x 9 inches",
      "shipping weight": "8.6 ounces",
      "ISBN-10": "1-948302-30-2",
      "ISBN-13": "978-1-948302-30-2",
      "url": "",
    },
    "hardcover": {
      "type": "Hardcover",
      "pages": "121",
      "publication date": "November 15, 2021",
      "dimensions": "6 x 0.5 x 9 inches",
      "shipping weight": "8.6 ounces",
      "ISBN-10": "1-948302-31-9",
      "ISBN-13": "978-1-948302-31-9",
      "url": "",
    },
    "kindle": {
      "type": "eBook",
      "size": "1971kb",
      "publication date": "November 15, 2021",
      "text-to-speech": "enabled",
      "x-ray": "not enabled",
      "word wise": "enabled",
      "lending": "enabled",
      "simultaneous device usage": "unlimited",
      "enhanced typesetting": "enabled",
      "ISBN-10": "1-948302-29-6",
      "ISBN-13": "978-1-948302-29-6",
      "url": "https://amzn.to/2WXah7R",
    },
    "categories": [
      "Philosophy",
      "Spiritual Science",
      "Modern Translations",
      "Coming Soon",
    ],
    "img": "FirstClassV2-01a_cov.jpg",
    "online":
      "https://wn.rsarchive.org/Lectures/GA270/English/eLib2018b/FstCs2_index.html",
  },
  {
    "id": "14",
    "title":
      "Esoteric Lessons for the First Class of the Free School for Spiritual Science at the Goetheanum (Volume Three)",
    "tsort":
      "Esoteric Lessons First Class Free School Spiritual Science Goetheanum Volume 3",
    "global": {
      "Author": "Rudolf Steiner",
      "Translator": "Frank Thomas Smith",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Anthroposophical Publications",
    },
    "paperback": {
      "type": "Paperback",
      "pages": "116",
      "publication date": "December 15, 2021",
      "dimensions": "6 x 0.5 x 9 inches",
      "shipping weight": "8.6 ounces",
      "ISBN-10": "n/a",
      "ISBN-13": "n/a",
      "url": "",
    },
    "hardcover": {
      "type": "Hardcover",
      "pages": "116",
      "publication date": "December 15, 2021",
      "dimensions": "6 x 0.5 x 9 inches",
      "shipping weight": "8.6 ounces",
      "ISBN-10": "n/a",
      "ISBN-13": "n/a",
      "url": "",
    },
    "kindle": {
      "type": "eBook",
      "size": "1971kb",
      "publication date": "December 15, 2021",
      "text-to-speech": "enabled",
      "x-ray": "not enabled",
      "word wise": "enabled",
      "lending": "enabled",
      "simultaneous device usage": "unlimited",
      "enhanced typesetting": "enabled",
      "ISBN-10": "n/a",
      "ISBN-13": "n/a",
      "url": "https://amzn.to/2WXah7R",
    },
    "categories": [
      "Philosophy",
      "Spiritual Science",
      "Modern Translations",
      "Coming Soon",
    ],
    "img": "FirstClassV3-01b_cov.jpg",
    "online":
      "https://wn.rsarchive.org/Lectures/GA270/English/eLib2018c/FstCs3_index.html",
  },
  {
    "id": "15",
    "title": "Artemis and the Artemision",
    "tsort": "Artemis Artemision",
    "sub-title": "the Mystery Centre at Ephesus",
    "global": {
      "Author": "Peter Stebbing",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Rudolf Steiner Publications",
    },
    "paperback": {
      "type": "Paperback",
      "pages": "28",
      "publication date": "November 10, 2021",
      "dimensions": "8.5 x 0.13 x 11.0 inches",
      "ISBN-10": "1-948302-18-0",
      "ISBN-13": "978-1-948302-18-0",
      "url": "",
    },
    "img": "ArtemisionCoverFront01.jpg",
    "categories": ["Social Science", "Coming Soon"],
    "online": "",
  },
  {
    "id": "16",
    "title": "Journey to the Stars",
    "tsort": "Journey Stars",
    "sub-title": "",
    "global": {
      "Author": "Frank Thomas Smith",
      "Editor": "James D. Stewart",
      "Language": "English",
      "Publisher": "Anthroposophical Publications",
    },
    "paperback": {
      "type": "Paperback",
      "pages": "122",
      "publication date": "December 15, 2021",
      "dimensions": "5.5 x 0.13 x 8.5 inches",
      "ISBN-10": "n/a",
      "ISBN-13": "n/a",
      "url": "",
    },
    "img": "journey-cov.jpg",
    "categories": ["Fiction", "Children's Books", "Coming Soon"],
    "online": "",
  },
]
