export const descriptions = [
  {
    id: 1,
    "long":
      "A reinvigorated translation by Frank Thomas Smith of Steiner's “Basic Issues of the Social Question,” number 23 in the Bibliography of 1961.<br><br>This work, written late in the life of Rudolf Steiner, makes use of a threefold analysis of the human individual and of human society. Man as an individual, or in a group, functions basically in three modes: thinking/perceiving, feeling/valuing, and willing/planning/acting. A unit of functioning, whether a part of an individual or part of a society has its proper role. Each role needs a certain respect from other areas if it is to function properly. Each role should be appropriately related to the other two roles or functions. In society, the three partitions are: the cultural-spiritual, the production-economic, and the “sphere of rights” including legal rights. As the analysis unfolds, it may be noticed that there is seldom a “pure case” but there are various mixes with one aspect often predominating. The manner in which the three aspects of society relate to the three aspects of the individual is a fascinating and intricate one, and one which has an important bearing on the future of human society.<br><br>This is not another “utopian” dialog, but a practical suggestion concerning details which may be incorporated into society one at a time ... from time to time. These suggestions are as relevant now as they were when Rudolf Steiner brought them forth over 100 years ago, just after the First World Was. At the end of the book, Steiner writes: “... either people will accommodate their thinking to the requirements of reality, or they will have learned nothing from the calamity and will cause innumerable new ones to occur in the future.” History has since proven these words to be prophetic.",
    "short":
      "This work, written late in the life of Rudolf Steiner, makes use of a threefold analysis of the human individual and of human society. Man as an individual, or in a group, functions basically in three modes: thinking/perceiving, feeling/valuing, and willing/planning/acting. A unit of functioning, whether a part of an individual or part of a society has its proper role. Each role needs a certain respect from other areas if it is to function properly...",
  },
  {
    id: 2,
    "long":
      "In content, this translation into English of Rudolf Steiner's lecture on the art historian, author and researcher Herman Grimm, can be said to be a paean to Grimm's wholly original and unorthodox approach to art history. Herman Grimm's work differs substantially from standard, more intellectual approaches, as becomes evident from statements of Herman Grimm quoted here:<br><br>If, by some miracle, Michelangelo were called from the dead, to live among us again, and if I were to meet him, I would humbly stand aside to let him pass: if Raphael came by, I would follow him, to see whether or not I might have the opportunity of hearing a few words from his lips. With Leonardo and Michelangelo, one can confine oneself to reporting what they once were in their day; with Raphael, one has to start from what he is for us today. Concerning the two others, a slight veil has passed over them, but not over Raphael. He belongs among those whose growth is as yet far from being at an end. We may imagine that Raphael will present ever new riddles to future generations of humanity.<br><br>This is a lecture, given by Rudolf Steiner, entitled Die Weltanschauung eines Kulturforschers der Gegenwart, Herman Grimm, und die Geistesforschung and contained in the volume Ergebnisse der Geistesforschung (Results of Spiritual Research) GA 62. The series in which this lecture was given at the Architektenhaus in Berlin, may be said to underline its overall importance for Rudolf Steiner: Held January 16th 1913 subsequent to a lecture January 30th on Raphael. Also known as, Herman Grimm, Contemporary Culture and Spiritual Developments, and Anthroposophy.<br><br>This lecture is the fourth in a series of four lectures from GA 62, that are newly translated by Peter Stebbing. Edited by James Stewart. You can research the on-line version of this book by clicking here. Or, click on the cover image to buy this book at Amazon.com, to read or study at home. ",
    "short":
      "In content, this translation into English of Rudolf Steiner's lecture on the art historian, author and researcher Herman Grimm, can be said to be a paean to Grimm's wholly original and unorthodox approach to art history. Herman Grimm's work differs substantially from standard, more intellectual approaches, as becomes evident from statements of Herman Grimm quoted here:",
  },
  {
    id: 3,
    "long":
      "Anthroposophy, also known as Spiritual Science, is not known for fantastic literature, or fiction at all. So how can stories with titles like “Life on Mars,” or “The Girl in the Floppy Hat,” or “To Hunt a Nazi” qualify as anthroposophical. They do not — until now. Therefore, this book is groundbreaking. You may smile at times, even laugh; other stories may cause a lump in your throat, perhaps even a tear or two. Oh, and by the way, fundamentalists are advised not to partake of this fantastical frosting on their anthroposophical cake.Here, then, are thirteen provocative, groundbreaking fictional tales for anthroposophists, and really anyone, to enjoy. By Roberto Fox, as told to Frank Thomas Smith. ",
    "short":
      "Anthroposophy, also known as Spiritual Science, is not known for fantastic literature, or fiction at all. So how can stories with titles like “Life on Mars,” or “The Girl in the Floppy Hat,” or “To Hunt a Nazi” qualify as anthroposophical. They do not — until now. Therefore, this book is groundbreaking. You may smile at times, even laugh; other stories may cause a lump in your throat...",
  },
  {
    id: 4,
    "long":
      "From the contents of this lecture: “Fairy tales and sagas are comparable to a good angel, granted human beings as a companion from birth on their life's wanderings, to be a trustworthy comrade throughout — offering comradeship, and making life inwardly into a truly ensouled fairy tale!<br><br> This is a lecture, given by Rudolf Steiner, entitled Märchendichtungen im Lichte der Geistesforschung, and contained in the volume Ergebnisse der Geistesforschung (Results of Spiritual Research) GA 62. The series in which this lecture was given at the Architektenhaus in Berlin, may be said to underline its overall importance for Rudolf Steiner: held February 6th 1913 subsequent to a lecture January 30th on Raphael, it was followed a week later, on February 13th, by a lecture on Leonardo da Vinci.<br><br>As a bonus, A Mongolian Legend is included. It is from a matinee lecture given by Rudolf Steiner: Mythen und Sagen. Okkulte Zeichen und Symbole (Myths and Legends. Occult Signs and Symbols). From GA 101. Lecture IV, 21st October 1907 in Berlin.<br><br>This lecture is the third in a series of four lectures from GA 62, that are newly translated by Peter Stebbing. Edited by James Stewart. You can research the on-line version of this book by clicking here. Or, click on the cover image to buy this book at Amazon.com, to read or study at home.",
    "short":
      "From the contents of this lecture: “Fairy tales and sagas are comparable to a good angel, granted human beings as a companion from birth on their life's wanderings, to be a trustworthy comrade throughout — offering comradeship, and making life inwardly into a truly ensouled fairy tale!” ",
  },
  {
    id: 5,
    "long":
      "“The three great masters of the Renaissance [Leonardo, Michelangelo, Raphael] strove to work in the spirit of that age. And the one who already had a kind of seed, I would say, that grew into everything that has come and is still to come since that time was Leonardo.” - Rudolf Steiner, Dornach, November 1, 1916. A single lecture given by Rudolf Steiner at Berlin on February 13th 1913, translated by Peter Stebbing, and edited by James D. Stewart, the e.Librarian at the The e.Lib, Inc. It is the eleventh of fourteen lectures in the volume entitled, Results of Spiritual Investigation, published in German as, Ergebnisse der Geistesforschung.<br><br>This lecture is the second in a series of four lectures from GA 62, that are newly translated by Peter Stebbing. Edited by James Stewart. Visit the on-line version of this book by clicking here. Or, click on the cover image to buy this book at Amazon.com, to read or study at home. ",
    "short":
      "“The three great masters of the Renaissance [Leonardo, Michelangelo, Raphael] strove to work in the spirit of that age. And the one who already had a kind of seed, I would say, that grew into everything that has come and is still to come since that time was Leonardo.” - Rudolf Steiner, Dornach, November 1, 1916.",
  },
  {
    id: 6,
    "long":
      "This is a First Edition English translation of a series of seven lectures, entitled The Impulse of Renewal for Culture and Science, and published in German as, Erneuerungs-Impuls fuer Kultur und Wissenschaft (Bn/GA/CW Number 81 in the Bibliographical Survey, 1961). This course was organized by the Federation of Anthroposophical University Work and the Berlin Branch of the Anthroposophical Society. It was the aim of the organizers, through lectures by various speakers, to “give an impression of what suggestions in various fields can be given by anthroposophy.” For each course day, Rudolf Steiner gave the introductory lecture. In these lectures, Steiner explains the relationships between Anthroposophy and the natural sciences, philosophy, pedagogy, theology, the social sciences, and linguistics. He also brings to light the biological differences between humans and animals from an anthroposophical perspective.<br><br> Visit the on-line version of this book by clicking here. Or, click on the cover image to buy this book at Amazon.com, to read or study at home. ",
    "short":
      "This is a First Edition English translation of a series of seven lectures, entitled The Impulse of Renewal for Culture and Science, and published in German as, Erneuerungs-Impuls fuer Kultur und Wissenschaft (Bn/GA/CW Number 81 in the Bibliographical Survey, 1961). This course was organized by the Federation of Anthroposophical University Work and the Berlin Branch of the Anthroposophical Society.",
  },
  {
    id: 7,
    "long":
      "This lecture on Raphael points to an ever greater inwardness or “internalizing” of the human soul in the future development of humanity. Steiner's large-format watercolours can be said to be an unmistakable further expression of this. Though it might seem improbable at first to link Raphael's works so directly with the painting impulse of Rudolf Steiner, separated as they are by four hundred years. An underlying relation becomes apparent, nonetheless, despite the manifest contrast. The Madonnas of Raphael will self-evidently never be surpassed. Yet, the future development of art, always “a daughter of the divine,” implies, in Rudolf Steiner's sense, an ongoing spiritualization. We begin to recognize Raphael's relevance for today and for the future. A lecture given by Rudolf Steiner: from Ergebnisse der Geistesforschung. (Some Results of Spiritual Research). Bn/GA/CW 62. Lecture IX, 30th January 1913 in Berlin.<br><br>This unique English translation is the first in a series of four lectures from GA 62, that are newly translated by Peter Stebbing. Edited by James Stewart. Visit the on-line version of this book by clicking here. Or, click on the cover image to buy this book at Amazon.com, to read or study at home. ",
    "short":
      "This lecture on Raphael points to an ever greater inwardness or “internalizing” of the human soul in the future development of humanity. Steiner's large-format watercolours can be said to be an unmistakable further expression of this. Though it might seem improbable at first to link Raphael's works so directly with the painting impulse of Rudolf Steiner, separated as they are by four hundred years...",
  },
  {
    id: 8,
    "long":
      "This book is a First Edition, never before translated into English, series of six lectures. Rudolf Steiner gave these lectures early in the year of 1919 at Zurich, Switzerland. Here Steiner proffers ideas to solve the social problems and necessities required by life, by studying the life sciences and social life, and the living conditions of the present-day humans. He expresses how the social will should be the basis of a new scientific order, and what the role of the modern worker should be.These six lectures are a translation from the German edition 'Die soziale Frage,' (Bn/GA/CW Number 328 in the Bibliographical Survey, 1961), published by the Rudolf Steiner-Nachlassverwaltung, Dornach, Switzerland, 1977. They are published as transcripts unrevised by the lecturer. This First English edition was translated by Hanna von Maltitz, and was edited by James D. Stewart, e.Librarian at the 'The e.Lib, Inc.' Illustrations and artwork were created by Hanna von Maltitz. Thanks to the Basil Gibaud Memorial Trust, this translation has been made available for everyone. The text of both the printed and eBook editions has numerous links to on-line web content that will enhance the reader/researcher in their understanding of the text: search all lectures, read/research the original German texts, compare the English translation to the original German paragraph by paragraph, and explore other related material. You can research Rudolf Steiner's works on-line ... buy the book to read and study at home.<br><br>Visit the on-line version of this book by clicking here. Or, click on the cover image to buy this book at Amazon.com, to read or study at home. ",
    "short":
      "This book is a First Edition, never before translated into English, series of six lectures. Rudolf Steiner gave these lectures early in the year of 1919 at Zurich, Switzerland. Here Steiner proffers ideas to solve the social problems and necessities required by life, by studying the life sciences and social life, and the living conditions of the present-day humans.",
  },
  {
    id: 9,
    "long":
      "Ute Craemer is an educator and social worker who has dedicated over fifty years of her life to teaching and nurturing the poor children of the favelas (slums) in Brazil. As an experienced Waldorf teacher, she has been able to understand the needs of the children and their families and provide them with the spiritual nourishment they cry out for. Favela Children is a moving and informative account of Ute's Craemer's social work in the favelas and of her personal development. It was originally published in German and went through several editions. It is published here for the first time in English.<br><br>Translated and with an introduction by Frank Thomas Smith. ",
    "short":
      "Ute Craemer is an educator and social worker who has dedicated over fifty years of her life to teaching and nurturing the poor children of the favelas (slums) in Brazil. As an experienced Waldorf teacher, she has been able to understand the needs of the children and their families and provide them with the spiritual nourishment they cry out for. Favela Children is a moving and informative account of Ute's Craemer's social work in the favelas and of her personal development...",
  },
  {
    id: 10,
    "long":
      "Sergio and his younger brother, Divino are poor children who live in a favela (slum) in Sao Paulo, Brazil. They go on vacation with their revered teacher, dona Ute (pronounced oo-teh), to the country house of one of Ute’s friends. Once there, they leave the house together to fetch kindling wood. They cross a stream and discover a strange round mound surrounded by white stones. Divino impetuously climbs the mound and convinces his brother to follow. Due to the mound’s magic forces, they fall asleep. They wake up in the land of Maxa. A girl, Mara, leads them through the jungle to her village where the meet the queen, Mamara. She tells them the history of the marvelous juice of immortality, vitaluz. They never grow old or die by drinking vitaluz, but never have children either. Queen Mamara and Princess Mara ask the boys to rescue Mireya, a young girl also from Brazil, who had been kidnapped by King Alaram. The boys agree to try, assisted by Platero, a white donkey as charming as he is stubborn, and a mysterious little man named Tamoshot. The search for Mireya is a dangerous adventure, but also the means of learning many important things about life. ",
    "short":
      "Sergio and his younger brother, Divino are poor children who live in a favela (slum) in Sao Paulo, Brazil. They go on vacation with their revered teacher, dona Ute (pronounced oo-teh), to the country house of one of Ute’s friends. Once there, they leave the house together to fetch kindling wood. They cross a stream and discover a strange round mound surrounded by white stones...",
  },
]
