<h1>About Anthroposophical Publications</h1>

<p>Anthroposophical Publications is pioneering a new publishing model: presenting documents online at the same time as hard copies are available for purchase: We are primarily (but not exclusively) concentrating on works with an Anthroposophical focus, including English translations of more than 2,500 Rudolf Steiner lectures that have never yet been translated. &#8220;Research Rudolf Steiner's works online ... buy the book to study at home.&#8221;</p>

<p>Rudolf Steiner, The Kingdom of Childhood, 20th August, 1924: &#8220;As to whether French and German should be taught from the beginning in an English School, I should first like to say that I think this must be settled entirely on grounds of expediency. If you simply find that life is making it necessary to teach these languages, you must teach them. We have introduced French and English into the Waldorf School, because with French there is much to be learnt from the inner quality of the language, not found elsewhere, namely, a certain feeling for rhetoric which it is very good to acquire: and English is taught because it is a universal world language, and will become so more and more.&#8221;</p>

<p>A number of translators from all over the world are volunteering their efforts, including Peter Stebbing, Frank Thomas Smith, Hanna von Maltitz, Luise M. Boeddinghaus, and Nesta Carsten.</p>

<p>This is also a venue for Anthroposophically-oriented authors to publish original works without paying to self-publish or by entering into disadvantageous arrangements with publishers.</p>

<p>Some volumes are currently available for purchase on Amazon and elsewhere, and we always have a number of works in process.</p>

<p><i>Anthroposophical Publications</i> and <i>Rudolf Steiner Publications</i> are imprints of <b>The e.Lib, Inc.</b> Our books are offered at reasonable prices made possible by print-on-demand technology.</p>
